# Generated by Django 2.1.1 on 2018-09-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('P_ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=50)),
                ('value', models.IntegerField(default=0)),
                ('DC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Distribution_centre')),
            ],
        ),
    ]
