# Generated by Django 2.1.1 on 2018-09-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_dealer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer_Address',
            fields=[
                ('zipcode', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('DL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Dealer')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Distance', models.IntegerField(default=0)),
                ('Quantity', models.IntegerField()),
                ('value', models.IntegerField()),
                ('DC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Distribution_centre')),
                ('DL_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Dealer')),
                ('P_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.product')),
            ],
        ),
    ]
