# Generated by Django 2.1.1 on 2018-10-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20181001_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='DC_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Distribution_centre'),
        ),
        migrations.AlterField(
            model_name='dealer_address',
            name='DL_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Dealer'),
        ),
        migrations.AlterField(
            model_name='distribution_centre_address',
            name='DC_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Distribution_centre'),
        ),
        migrations.AlterField(
            model_name='distribution_centre_location',
            name='DC_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Distribution_centre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='DC_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Distribution_centre'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='DC_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Distribution_centre'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='DL_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Dealer'),
        ),
        migrations.AlterField(
            model_name='ship',
            name='P_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.product'),
        ),
    ]
