# Generated by Django 2.1.1 on 2018-10-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20181002_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='value',
        ),
        migrations.AlterField(
            model_name='dealer',
            name='Contact',
            field=models.CharField(max_length=15),
        ),
    ]
